language: bash
sudo: false
dist: trusty

jdk:
  - openjdk8
  
script:
  - echo "testing11"
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn -DtestSourceDirectory=test/regression/ -Dtest=SmartMutationTest test -DfailIfNoTests=false -pl EvosuiteTest -e
