language: bash
sudo: false

jdk:
  - oraclejdk8
  
dist: trusty

script:
  - echo "testing11"
  - mvn -DtestSourceDirectory=test/regression/ -Dtest=SmartMutationTest test -DfailIfNoTests=false -pl EvosuiteTest -e
